#! /usr/bin/python

import sys, cgi
sys.path.append("../msconfig")
import CGIUtils
sys.path.append("../var")
from Config import MAPSERVER_EXE

params = cgi.FieldStorage()

layerName = str(params.getvalue("LAYERS")).split('Mask')[0]

MAPFILE = '../msconfig/dyna_maps/'+layerName+'.map'

CGIUtils.mapserv_inject_mapfile(MAPFILE, MAPSERVER_EXE)
