#! /usr/bin/python

import sys, cgi, cgitb
sys.path.append("../msconfig")
import CGIUtils
sys.path.append("../var")
from Config import MAPSERVER_EXE

cgitb.enable()

params = cgi.FieldStorage()

# Workaround for integrating WMS service into ArcGIS Online
if 'MAPFILE' in params:
	mapfileName = str(params.getvalue("MAPFILE"))
else:
	mapfileName = str(params.getvalue("LAYERS")).split('Mask')[0].rstrip('_')

MAPFILE = '../msconfig/forwarn2_maps/'+mapfileName+'.map'

CGIUtils.mapserv_inject_mapfile(MAPFILE, MAPSERVER_EXE)
