#! /usr/bin/python

import sys, cgi, cgitb
sys.path.append("../msconfig")
import CGIUtils
sys.path.append("../var")
from Config import MAPSERVER_EXE

cgitb.enable()

params = cgi.FieldStorage()

# Workaround for integrating WMS service into ArcGIS Online
if 'MAPFILE' in params:
    param = "MAPFILE"
# For WCS requests: extract  mapfile name from param
elif 'COVERAGE' in params:
    param = "COVERAGE"
# Assume we're dealing with a WMS request
else:
    param = "LAYERS"

mapfileName = str(params.getvalue(param)).split('Mask')[0].rstrip('_')

MAPFILE = '../msconfig/forwarn3_maps/'+mapfileName+'.map'

CGIUtils.mapserv_inject_mapfile(MAPFILE, MAPSERVER_EXE)
