#! /usr/bin/python

### creates the mapfile:
###    {ews.map,ewswgs84.map,ewswcs.map etc...}
### from the template files
###    ews.map.tmpl   - template for whole mapfile
###    ews.layer.tmpl - template for each layer section
### by looping over all tif files found in
###    * LAYER_DATA_DIR
###    * DATA_DIR/fsdata/efetac_nasa/ews
### 
###  * create ews1year.map using template ews1year.tpl.map
###  * create ews3year.map using template ews3year.tpl.map
###  * create ews5year.map using template ews5year.tpl.map
###  * create ewstruecolor.map using template ewstruecolor.tpl.map


###
### imports
###

#print "debug: at 1"

from osgeo import gdal, osr
import sys, os, subprocess, datetime, re, shutil, traceback, getopt;

opts, args = getopt.getopt(sys.argv[1:],"al")

use_all_lands = False
for opt, arg in opts:
    if opt in ("-al"):
        use_all_lands = True
        print "Using All-Lands"


def choose(al,fo):
    if use_all_lands:
        return al
    else:
        print "Using Forest-Only"
        return fo

#print "debug: at 2"

###
### config
###

sys.path.append("../var")
try:
    from Config import *
except:
    print "Cannot find local settings file 'Config.py'.  You need to create a Config.py file that contains"
    print "settings appropriate for this copy of the FSWMS project.  You can use the file 'Config.tpl.py'"
    print "as a starting point --- make a copy of that file called 'Config.py', and edit appropriately."
    exit(-1)

from LegendConfig import *

#print "debug: at 3"

# jdm 5/9/13: for each of these go through the ewsMask and create a relavent entry
# these should be read out of an external config file but I have hardcoded for now
ewsMask = [
    {'name' : 'MaskForForest'},
    {'name' : 'MaskForAgriculture'},
    {'name' : 'MaskForConiferForest'},
    {'name' : 'MaskForDeciduousForest'},
    {'name' : 'MaskForGrass'},
    {'name' : 'MaskForMixedForest'},
    {'name' : 'MaskForNonVegetated'},
    {'name' : 'MaskForShrubland'},
    {'name' : 'MaskForUrban'},
    {'name' : 'MaskForWetland'}
    ]   

###
### function definitions
###

#print "debug: at 4"

def rfind(dir, pattern):
    """Recursive find: returns a list of all files located in a directory or any of its descendent directories,
    and whose names match a regular expression pattern."""
    files = []
    for file in os.listdir(dir):
        if os.path.isdir(os.path.join(dir, file)):
            files = files + rfind(os.path.join(dir,file), pattern)
        if re.match(pattern, file):
            files.append(os.path.join(dir,file))
    return files

def getproj(tif):
    projectionWkt = getwkt(tif)
    spatialReferenceObj = osr.SpatialReference(projectionWkt)
    projectionProj4 = spatialReferenceObj.ExportToProj4()
    return projectionProj4

def interp(string):
  locals  = sys._getframe(1).f_locals
  globals = sys._getframe(1).f_globals
  for item in re.findall(r'#\{([^{]*)\}', string):
    string = string.replace('#{%s}' % item,
                            str(eval(item, globals, locals)))
  return string

def getwkt(tif):

    #function to get the well known text version of the
    #  spatail reference (proejction) of the image (tif)
    wktFile = tif + '.wkt'
    wktData = ''

    #check if a wkt tile exists
    wktFileExists = os.path.exists(wktFile)

    if wktFileExists:
        #if the wkt file exists read the file
        #  trying to avoid doing gdal.open its resource expensive
        #  doing a normal file read of the of MUCH smaller text file seems to speed things up
        with open(wktFile, 'r') as myfile:
            wktData = myfile.read()

    else:
        #if the wkt file does not exist thane use gdal to write it.
        dataSet = gdal.Open( tif, gdal.GA_ReadOnly )
        wktData = dataSet.GetProjection()
        f = open( wktFile, 'w' )
        f.write( wktData )
        f.close()

    return wktData

#mark out for testing new function above
#def getwkt(tif):
#    dataSet = gdal.Open( tif, gdal.GA_ReadOnly )
#    return dataSet.GetProjection()

# formatproj reformats a "proj4" projection string into the form required by a Mapserver mapfile.
# Specifically, it splits it into one expression per line, delimited by double quotes.  It takes
# an optional indentation level, and indents the returned string by that number of spaces.
def formatproj(projstring, indentlevel=0):
    answer = ""
    indentation = " "*indentlevel
    lines = []
    for line in re.split(r'\s+', projstring):
        if line != "":
            lines.append("%s%s\"%s\"" % (answer, indentation, line))
    return "\n".join(lines)

# getModDate gets the date when a file was last edited and formats that timestamp in a readable form
def getModDate(filename):
    t = os.stat(filename).st_mtime
    return datetime.datetime.fromtimestamp(t)

class Template:
    def __init__(self, file):
        f = open(file, "r")
        self.contents = ""
        for line in f:
            self.contents = self.contents + line
        f.close
    def render(self, dict):
        return self.contents % dict

#print "debug: at 5"

#Start of attempt to create a generic function to get layers
#At this point its a not completely generic because the color maps is 
#specific to the tif files location
#LAYERS1 = getLayers(DATA_DIR + "/fsdata/efetac_nasa/"+choose("X_LC_1YEAR", "1Year"), "ews_gen.layer.tpl.map", "EFETAC-NASA_1Year", ".tif", "no", True)
def getLayers(dataDir, layerTemplateName, groupName, fileExt, wcs, maskBool):
    #print 'data dir ' + dataDir
    #print 'template ' + layerTemplateName
    tifList  = []
    for tif in sorted([file for file in os.listdir(dataDir) if file.endswith(fileExt)], reverse=False):
        dynaList  = []
        try:        
            tif = re.sub('^' + dataDir + '/', '', tif)
            tif_fullpath = dataDir + '/' + tif;
            proj = getproj(tif_fullpath)
            modDate = getModDate(tif_fullpath)
            nameform = re.sub(r'^.*/', '', tif)
            #print nameform
            #this conditional logic needs to be refactored out
            if re.search(r'max|med', nameform) and wcs=="no":
                colormapline   = 'INCLUDE "new-forwarn2-standard-2.cmap"'
            elif re.search(r'255c.img', nameform):
                colormapline   = ''
            elif re.search(r'u16b.img', nameform):
                colormapline   = 'INCLUDE "truecolor16b.cmap"'  
            #elif re.search(r'.img', fileExt):
                #colormapline   = ''
            elif(wcs=="yes"):
                colormapline   = ''
            else:
                colormapline   = 'INCLUDE "new-forwarn2-standard-2.cmap"'
            group = groupName 
            if re.search(r'.img', nameform):
                layerName = group + "_" + re.sub(r'_([^_]*_[^_]*)$', '', nameform)
            else:
                #jdm 1/26 check for the occurace of bd after the last underscore
                #this is the same layer but w/ a slightly diff algorithm on the remote
                #sensing side of things.
                if re.sub(r'/.*\/|.*_|\.tif$', '', nameform) == "bd":
                    layerName = group + "_" + re.sub(r'_.*$', '', nameform) + "bd"
                else:
                    layerName = group + "_" + re.sub(r'_.*$', '', nameform)
            layerTitle = tif
            tifList.append({ 'TIF'             : tif,
                             'PROJVALID'       : len(proj) > 0,
                             'PROJ'            : formatproj(proj,10),
                             'WKT'             : getwkt(tif_fullpath),
                             'NAME'            : layerName,
                             'GROUP'           : group,
                             'DATA'            : dataDir + '/' + tif,
                             'TITLE'           : layerTitle,
                             'ABSTRACT'        : layerTitle,
                             'COLORMAPLINE'    : colormapline,
                             'MASK'            : '',
                             })
            dynaList.append({ 'TIF'             : tif,
                             'PROJVALID'       : len(proj) > 0,
                             'PROJ'            : formatproj(proj,10),
                             'WKT'             : getwkt(tif_fullpath),
                             'NAME'            : layerName,
                             'GROUP'           : group,
                             'DATA'            : dataDir + '/' + tif,
                             'TITLE'           : layerTitle,
                             'ABSTRACT'        : layerTitle,
                             'COLORMAPLINE'    : colormapline,
                             'MASK'            : '',
                             })                             
            layerTitles[layerName] = layerTitle
            #jdm 5/29: for layers groups that we want ewsMask on do so     
            if maskBool:
                #print "got here"
                for mask in ewsMask:
                    #print "test mask: " + layerName + mask['name']
                    #print proj
                    #print len(proj) > 0
                    tifList.append({ 'TIF'             : tif,
                                     'PROJVALID'       : len(proj) > 0,
                                     'PROJ'            : formatproj(proj,10),
                                     'WKT'             : getwkt(tif_fullpath),
                                     'NAME'            : layerName + mask['name'],
                                     'GROUP'           : group,
                                     'DATA'            : dataDir + '/' + tif,
                                     'TITLE'           : layerTitle + mask['name'],
                                     'ABSTRACT'        : layerTitle + mask['name'],
                                     'COLORMAPLINE'    : colormapline,
                                     'MASK'            : 'MASK ' + mask['name'],
                                     })    
                    dynaList.append({ 'TIF'             : tif,
                                     'PROJVALID'       : len(proj) > 0,
                                     'PROJ'            : formatproj(proj,10),
                                     'WKT'             : getwkt(tif_fullpath),
                                     'NAME'            : layerName + mask['name'],
                                     'GROUP'           : group,
                                     'DATA'            : dataDir + '/' + tif,
                                     'TITLE'           : layerTitle + mask['name'],
                                     'ABSTRACT'        : layerTitle + mask['name'],
                                     'COLORMAPLINE'    : colormapline,
                                     'MASK'            : 'MASK ' + mask['name'],
                                     })                                          
            #Perform layer-level creation of dynamic map files:
            layerTemplate = Template(layerTemplateName)
            layers = ""
            for tifdict in dynaList:
                if tifdict['PROJVALID']:
                    layers = layers + layerTemplate.render(tifdict)    
                    mapTemplate = Template("ews.map.tmpl")
                    SERVICE_NAME = "dyna_ews"
                    f_new = openMapfileForWriting("dyna_maps/"+layerName+".map")
                    f_new.write( mapTemplate.render( {
                                'DATA_DIR'                : DATA_DIR,
                                'LAYERS'                  : layers,
                                'WMS_SRS'                 : "EPSG:3857 EPSG:4326 EPSG:900913",
                                'MAPFILE_PROJECTION'      : '"init=epsg:3857"',
                                'SERVICE_NAME'            : SERVICE_NAME,
                                'TEMP_FILE_PREFIX'        : "ms_%s" % (SERVICE_NAME),
                                'MAPFILE'                 : "%s/msconfig/%s.map" % (BASE_DIR, SERVICE_NAME),
                                'OWS_TITLE'               : "NEMAC %s WMS" % (SERVICE_NAME),
                                'OWS_ABSTRACT'            : "NEMAC %s WMS" % (SERVICE_NAME),
                                'OWS_KEYWORDLIST'         : "mapserver,ogc,%s" % (SERVICE_NAME),
                                'SERVICE_URL'             : "%s/%s" % (SERVER_URL, SERVICE_NAME),
                                'MS_ERRORFILE'            : "../var/log/%s.log" % (SERVICE_NAME),
                                'WFS_NAMESPACE_PREFIX'    : SERVICE_NAME
                                } ) )
                    f_new.close()                    
        except Exception as e:
            print e
            continue
    layerTemplate = Template(layerTemplateName)
    layers = ""
    for tifdict in tifList:
        if tifdict['PROJVALID']:
            layers = layers + layerTemplate.render(tifdict)    
    return layers

def getLayersNoMask(dataDir, layerTemplateName, groupName, fileExt, wcs, maskBool):
    tifList  = []
    for tif in sorted([file for file in os.listdir(dataDir) if file.endswith(fileExt)], reverse=False):
        dynaList  = []
        try:        
            tif = re.sub('^' + dataDir + '/', '', tif)
            tif_fullpath = dataDir + '/' + tif;
            proj = getproj(tif_fullpath)
            modDate = getModDate(tif_fullpath)
            nameform = re.sub(r'^.*/', '', tif)
            #print nameform
            #this conditional logic needs to be refactored out
            if re.search(r'max|med', nameform) and wcs=="no":
                colormapline   = 'INCLUDE "new-forwarn2-standard-2.cmap"'
            elif re.search(r'255c.img', nameform):
                colormapline   = ''
            elif re.search(r'u16b.img', nameform):
                colormapline   = 'INCLUDE "truecolor16b.cmap"'  
            #elif re.search(r'.img', fileExt):
                #colormapline   = ''
            elif(wcs=="yes"):
                colormapline   = ''
            else:
                colormapline   = 'INCLUDE "new-forwarn2-standard-2.cmap"'
            group = groupName 
            if re.search(r'.img', nameform):
                layerName = group + "_" + re.sub(r'_([^_]*_[^_]*)$', '', nameform)
            else:
                #jdm 1/26 check for the occurace of bd after the last underscore
                #this is the same layer but w/ a slightly diff algorithm on the remote
                #sensing side of things.
                if re.sub(r'/.*\/|.*_|\.tif$', '', nameform) == "bd":
                    layerName = group + "_" + re.sub(r'_.*$', '', nameform) + "bd"
                else:
                    layerName = group + "_" + re.sub(r'_.*$', '', nameform)
            layerTitle = tif
            tifList.append({ 'TIF'             : tif,
                             'PROJVALID'       : len(proj) > 0,
                             'PROJ'            : formatproj(proj,10),
                             'WKT'             : getwkt(tif_fullpath),
                             'NAME'            : layerName,
                             'GROUP'           : group,
                             'DATA'            : dataDir + '/' + tif,
                             'TITLE'           : layerTitle,
                             'ABSTRACT'        : layerTitle,
                             'COLORMAPLINE'    : colormapline,
                             'MASK'            : '',
                             })                           
            layerTitles[layerName] = layerTitle
            #jdm 5/29: for layers groups that we want ewsMask on do so     
            if maskBool:
                #print "got here"
                for mask in ewsMask:
                    #print "test mask: " + layerName + mask['name']
                    #print proj
                    #print len(proj) > 0
                    tifList.append({ 'TIF'             : tif,
                                     'PROJVALID'       : len(proj) > 0,
                                     'PROJ'            : formatproj(proj,10),
                                     'WKT'             : getwkt(tif_fullpath),
                                     'NAME'            : layerName + mask['name'],
                                     'GROUP'           : group,
                                     'DATA'            : dataDir + '/' + tif,
                                     'TITLE'           : layerTitle + mask['name'],
                                     'ABSTRACT'        : layerTitle + mask['name'],
                                     'COLORMAPLINE'    : colormapline,
                                     'MASK'            : 'MASK ' + mask['name'],
                                     })                                                              
        except Exception as e:
            print e
            continue
    layerTemplate = Template(layerTemplateName)
    layers = ""
    for tifdict in tifList:
        if tifdict['PROJVALID']:
            layers = layers + layerTemplate.render(tifdict)    
    return layers

#print "debug: at 6"

mapfilesWritten = []

###
### This function simply opens a file for writing, and appends the name of the file
### to the mapfilesWritten array, which is used at the bottom of this script to
### write the index.html file with the list of all the WMS addresses.
###
def openMapfileForWriting(filename):
    mapfilesWritten.append(filename)
    return open(filename, "w");
    
### Begining of run-time code -------************************************
###
### initialize a dict to keep track of layer titles (keyed by layer name):
###
layerTitles = {}

###
### initialize tiflist: array of dict objects holding info about each layer in mapfile(s)
###
tiflist = []

#print "debug: at 7"

###
### create a tiflist entry for each .tif file in LAYER_DATA_DIR:
### these are symlinks of the most recent 3 
###
retroPattern = r'-retro/(.+)/'
#print "debug: LAYER_DATA_DIR=%s" % LAYER_DATA_DIR
for tif in rfind(LAYER_DATA_DIR, r'^.*\.tif$'):
    #print "debug: at 7.1"
    dynaList  = []
    tif = re.sub('^' + LAYER_DATA_DIR + '/', '', tif)
    m = re.search(retroPattern, tif)
    #print "debug: at 7.2"
    if m != None:
        baseLineFolder = m.group(1) + "_"
    else:
        baseLineFolder = ""
    tif_fullpath = LAYER_DATA_DIR + '/' + tif;

    #print "debug: at 7.3"
    try:
        proj = getproj(tif_fullpath)
    except:
        continue

    #print "debug: at 7.4"
    if tif.startswith("rsac"):
        group          = "RSAC-FHTET"
        group_abstract = "Layers uploaded by RSAC-FHTET"
        colormapfile   = "new-forwarn2-standard-2.cmap"
        colormapcsv    = "rsac_fhtet_percent_change_cmap.csv"
        keyimage       = "cmapicons/new-forwarn2-standard-legend-2.png"
    else:
        group          = "EFETAC-NASA"
        group_abstract = "Layers uploaded by TACs-NASA"
        colormapfile   = "new-forwarn2-standard-2.cmap"
        colormapcsv    = "efetac_nasa_percent_change_cmap.csv"
        keyimage       = "cmapicons/new-forwarn2-standard-legend-2.png"

    #print "debug: at 7.5"
    modDate = getModDate(tif_fullpath)
    nameform = re.sub(r'^.*/', '', tif)
    nameformStart = re.sub(r'_.*$', '', nameform)
    layerNameForm = nameformStart

    #print "debug: at 7.6"
    layerName  = group + "_" + baseLineFolder + layerNameForm    # change this to be like "EFETAC-NASA_3yr-baseline_current"
    layerTitle = tif
    tiflist.append({ 'TIF'             : tif,
                     'PROJVALID'       : len(proj) > 0,
                     'PROJ'            : formatproj(proj,10),
                     'WKT'             : getwkt(tif_fullpath),
                     'NAME'            : layerName,
                     'GROUP'           : group,
                     'DATA'            : LAYER_DATA_DIR + '/' + tif,
                     'GROUP_ABSTRACT'  : group_abstract,
                     'TITLE'           : layerTitle, # change to be desired layer title in the viewer, e.g. efetac_nasa-retro/3YrBaseline/current_december3_december26.tif
                     'ABSTRACT'        : layerTitle, # change this to match title 
                     'COLORMAPFILE'    : colormapfile,
                     'COLORMAPCSV'     : colormapcsv,
                     'KEYIMAGE'        : keyimage,
                     'MODDATE'         : modDate,
                     'MASK'            : ''
                    })
    #print "debug: at 7.7"
    dynaList.append({ 'TIF'             : tif,
                     'PROJVALID'       : len(proj) > 0,
                     'PROJ'            : formatproj(proj,10),
                     'WKT'             : getwkt(tif_fullpath),
                     'NAME'            : layerName,
                     'GROUP'           : group,
                     'DATA'            : LAYER_DATA_DIR + '/' + tif,
                     'GROUP_ABSTRACT'  : group_abstract,
                     'TITLE'           : layerTitle, # change to be desired layer title in the viewer, e.g. efetac_nasa-retro/3YrBaseline/current_december3_december26.tif
                     'ABSTRACT'        : layerTitle, # change this to match title 
                     'COLORMAPFILE'    : colormapfile,
                     'COLORMAPCSV'     : colormapcsv,
                     'KEYIMAGE'        : keyimage,
                     'MODDATE'         : modDate,
                     'MASK'            : ''
                    })                    
    layerTitles[layerName] = layerTitle
    #print "debug: at 7.8"
    
    #Mask are only for tacs nasa products
    if not tif.startswith("rsac"):
        for mask in ewsMask:
            tiflist.append({ 'TIF'             : tif,
                             'PROJVALID'       : len(proj) > 0,
                             'PROJ'            : formatproj(proj,10),
                             'WKT'             : getwkt(tif_fullpath),
                             'NAME'            : layerName + mask['name'],
                             'GROUP'           : group,
                             'DATA'            : LAYER_DATA_DIR + '/' + tif,
                             'GROUP_ABSTRACT'  : group_abstract,
                             'TITLE'           : layerTitle + mask['name'], # change to be desired layer title in the viewer, e.g. efetac_nasa-retro/3YrBaseline/current_december3_december26.tif
                             'ABSTRACT'        : layerTitle + mask['name'], # change this to match title 
                             'COLORMAPFILE'    : colormapfile,
                             'COLORMAPCSV'     : colormapcsv,
                             'KEYIMAGE'        : keyimage,
                             'MODDATE'         : modDate,
                             'MASK'            : 'MASK ' + mask['name']
                             })
            dynaList.append({ 'TIF'             : tif,
                             'PROJVALID'       : len(proj) > 0,
                             'PROJ'            : formatproj(proj,10),
                             'WKT'             : getwkt(tif_fullpath),
                             'NAME'            : layerName + mask['name'],
                             'GROUP'           : group,
                             'DATA'            : LAYER_DATA_DIR + '/' + tif,
                             'GROUP_ABSTRACT'  : group_abstract,
                             'TITLE'           : layerTitle + mask['name'], # change to be desired layer title in the viewer, e.g. efetac_nasa-retro/3YrBaseline/current_december3_december26.tif
                             'ABSTRACT'        : layerTitle + mask['name'], # change this to match title 
                             'COLORMAPFILE'    : colormapfile,
                             'COLORMAPCSV'     : colormapcsv,
                             'KEYIMAGE'        : keyimage,
                             'MODDATE'         : modDate,
                             'MASK'            : 'MASK ' + mask['name']
                             })  
    #print "debug: at 7.9"
    #Perform layer-level creation of dynamic map files:
    layerTemplate = Template("ews.layer.tmpl")
    layers = ""
    for tifdict in dynaList:
        #if layerName != "EFETAC-NASA_1YrBaseline_previous1":
        #    continue
        if tifdict['PROJVALID']:
            #print "1: yaya layerName = %s" % layerName
            #print tifdict
            layers = layers + layerTemplate.render(tifdict)    
            mapTemplate = Template("ews.map.tmpl")
            SERVICE_NAME = "dyna_ews"
            THIS_MAPFILE="dyna_maps/"+layerName+".map"
            #print "writing mapfile: %s" % THIS_MAPFILE
            f_new = openMapfileForWriting(THIS_MAPFILE)
            THIS_DATA = mapTemplate.render( {
                        'DATA_DIR'                : DATA_DIR,
                        'LAYERS'                  : layers,
                        'WMS_SRS'                 : "EPSG:3857 EPSG:4326 EPSG:900913",
                        'MAPFILE_PROJECTION'      : '"init=epsg:3857"',
                        'SERVICE_NAME'            : SERVICE_NAME,
                        'TEMP_FILE_PREFIX'        : "ms_%s" % (SERVICE_NAME),
                        'MAPFILE'                 : "%s/msconfig/%s.map" % (BASE_DIR, SERVICE_NAME),
                        'OWS_TITLE'               : "NEMAC %s WMS" % (SERVICE_NAME),
                        'OWS_ABSTRACT'            : "NEMAC %s WMS" % (SERVICE_NAME),
                        'OWS_KEYWORDLIST'         : "mapserver,ogc,%s" % (SERVICE_NAME),
                        'SERVICE_URL'             : "%s/%s" % (SERVER_URL, SERVICE_NAME),
                        'MS_ERRORFILE'            : "../var/log/%s.log" % (SERVICE_NAME),
                        'WFS_NAMESPACE_PREFIX'    : SERVICE_NAME
                        } )
            #print THIS_DATA
            f_new.write( THIS_DATA )
            f_new.close() 
                             
###
### create a tiflist entry for each .tif file in DATA_DIR+"/fsdata/efetac_nasa/ews:
### these are the actual data files as they are dropped off via ftp
###
ARCHIVE_DIR = DATA_DIR + "/fsdata/efetac_nasa/"+choose("X_LC_ALLYEAR", "AllYear") #DATA_DIR is "/flood" currently
for tif in sorted([file for file in os.listdir(ARCHIVE_DIR) if file.endswith(".tif")], reverse=False):
    try:
        tif = re.sub('^' + ARCHIVE_DIR + '/', '', tif)
        tif_fullpath = ARCHIVE_DIR + '/' + tif;
        proj = getproj(tif_fullpath)
        modDate = getModDate(tif_fullpath)
        nameform = re.sub(r'^.*/', '', tif)
        if tif.startswith("rsac"): #jdm: I don't think this if is needed Marked4Delete
            group = "RSAC-FHTET"
            group_abstract = "Layers uploaded by RSAC-FHTET"
            colormapfile   = "new-forwarn2-standard-2.cmap"
            colormapcsv    = "rsac_fhtet_percent_change_cmap.csv"
            keyimage       = "cmapicons/new-forwarn2-standard-legend-2.png"
            print 'jdm: see this never prints'
        else:
            group = "EFETAC-NASA"
            group_abstract = "Layers uploaded by TACs-NASA"
            colormapfile   = "new-forwarn2-standard-2.cmap"
            colormapcsv    = "efetac_nasa_percent_change_cmap.csv"
            keyimage       = "cmapicons/new-forwarn2-standard-legend-2.png"
        layerName  = group + "_" + re.sub(r'_.*$', '', nameform)
        layerTitle = tif

        #jdm 1/27 if it is a 2010 file use the old color map
        if re.search(r'2010', nameform):
            colormapfile = "ewsold.cmap"

        tiflist.append({ 'TIF'             : tif,
                         'PROJVALID'       : len(proj) > 0,
                         'PROJ'            : formatproj(proj,10),
                         'WKT'             : getwkt(tif_fullpath),
                         'NAME'            : layerName,
                         'GROUP'           : group,
                         'DATA'            : ARCHIVE_DIR + '/' + tif,
                         'GROUP_ABSTRACT'  : group_abstract,
                         'TITLE'           : layerTitle,
                         'ABSTRACT'        : layerTitle,
                         'COLORMAPFILE'    : colormapfile,
                         'COLORMAPCSV'     : colormapcsv,
                         'KEYIMAGE'        : keyimage,
                         'MODDATE'         : modDate,
                         'MASK'            : ''
                         })
        layerTitles[layerName] = layerTitle

        for mask in ewsMask:
            tiflist.append({ 'TIF'             : tif,
                             'PROJVALID'       : len(proj) > 0,
                             'PROJ'            : formatproj(proj,10),
                             'WKT'             : getwkt(tif_fullpath),
                             'NAME'            : layerName + mask['name'],
                             'GROUP'           : group,
                             'DATA'            : ARCHIVE_DIR + '/' + tif,
                             'GROUP_ABSTRACT'  : group_abstract,
                             'TITLE'           : layerTitle + mask['name'], # change to be desired layer title in the viewer, e.g. efetac_nasa-retro/3YrBaseline/current_december3_december26.tif
                             'ABSTRACT'        : layerTitle + mask['name'], # change this to match title 
                             'COLORMAPFILE'    : colormapfile,
                             'COLORMAPCSV'     : colormapcsv,
                             'KEYIMAGE'        : keyimage,
                             'MODDATE'         : modDate,
                             'MASK'            : 'MASK ' + mask['name']
                             })    
    except:
        continue

#print "debug: at 9"

###
### add in the rsac fhtet files to be available in an archive format
### these will go in ews.map also but will utilize a diff color map: rsac_fhtet_percent_change_cmap.cmap
###
ARCHIVE_DIR = DATA_DIR + "/fsdata/rsac_fhtet/ews" #DATA_DIR is "/flood" currently
for tif in sorted([file for file in os.listdir(ARCHIVE_DIR) if file.endswith(".tif")], reverse=False):
    try:
        tif = re.sub('^' + ARCHIVE_DIR + '/', '', tif)
        tif_fullpath = ARCHIVE_DIR + '/' + tif;
        proj = getproj(tif_fullpath)
        modDate = getModDate(tif_fullpath)
        nameform = re.sub(r'^.*/', '', tif)
        if ('3yr') in nameform or ('5yr') in nameform:
            group = "RSAC-FHTET"
            group_abstract = "Layers uploaded by RSAC-FHTET"
            colormapfile   = "rsac_fhtet_percent_change_cmap.cmap"
            colormapcsv    = "rsac_fhtet_percent_change_cmap.csv"
            #keyimage       = "RSAC-FHTET_CT_7-6-2011_clipped.png"
            keyimage       = "cmapicons/RSAC-FHTET_CT_7-6-2011_clipped.png"
            if re.sub(r'/.*\/|.*_|\.tif$', '', nameform) == "bd":
                layerName = group + "_" + re.sub(r'_.*$', '', nameform) + "bd"
            else:
                layerName = group + "_" + re.sub(r'_.*$', '', nameform)
            if '3yr' in nameform:
                layerName = layerName + "3yr"
            else:
                layerName = layerName + "5yr"
            layerTitle = tif
            tiflist.append({ 'TIF'             : tif,
                             'PROJVALID'       : len(proj) > 0,
                             'PROJ'            : formatproj(proj,10),
                             'WKT'             : getwkt(tif_fullpath),
                             'NAME'            : layerName,
                             'GROUP'           : group,
                             'DATA'            : ARCHIVE_DIR + '/' + tif,
                             'GROUP_ABSTRACT'  : group_abstract,
                             'TITLE'           : layerTitle,
                             'ABSTRACT'        : layerTitle,
                             'COLORMAPFILE'    : colormapfile,
                             'COLORMAPCSV'     : colormapcsv,
                             'KEYIMAGE'        : keyimage,
                             'MODDATE'         : modDate,
                             'MASK'            : ''
                             })
            layerTitles[layerName] = layerTitle 
    except:
        print 'except occured'
        continue



######################################

###
### build the LAYERS string by appending a rendered layer template for each valid layer:
###
layerTemplate = Template("ews.layer.tmpl")
LAYERS = ""
for tifdict in tiflist:
    if tifdict['PROJVALID']:
        print tifdict['NAME']
        LAYERS = LAYERS + layerTemplate.render( tifdict )

LAYERS1 = LAYERS
        
###
### Append to ews.map FILE Seasonally-Adjusted Change from All-Year pheno-cluster max (MUC):
###
LAYERS2 = getLayers(DATA_DIR + "/fsdata/efetac_nasa/"+ "X_LC_MUC_ALL_YR", "ews_gen.layer.tpl.map", "EFETAC-NASA_MUCAllYear", ".tif", "no", True)
LAYERS2_NOMASK = getLayersNoMask(DATA_DIR + "/fsdata/efetac_nasa/"+ "X_LC_MUC_ALL_YR", "ews_gen.layer.tpl.map", "EFETAC-NASA_MUCAllYear", ".tif", "no", False)
LAYERS2_NOMASK_FW2_LEIDOS = getLayersNoMask(FW2_DATA_DIR + "/Leidos/" + "X_LC_1YEAR", "ews_gen.layer.tpl.map", "EFETAC-NASA_MUCAllYear", ".tif", "no", False)
LAYERS2_NOMASK = LAYERS2_NOMASK + LAYERS2_NOMASK_FW2_LEIDOS

###
### Append to ews.map FILE Seasonally-Adjusted Change from All-Year mean of maximums (MMAX):
###
LAYERS3 = getLayers(DATA_DIR + "/fsdata/efetac_nasa/"+ "X_LC_MMAX_ALL_YR", "ews_gen.layer.tpl.map", "EFETAC-NASA_MoMAllYear", ".tif", "no", True)
LAYERS3_NOMASK = getLayersNoMask(DATA_DIR + "/fsdata/efetac_nasa/"+ "X_LC_MMAX_ALL_YR", "ews_gen.layer.tpl.map", "EFETAC-NASA_MoMAllYear", ".tif", "no", False)
LAYERS3_NOMASK_FW2_LEIDOS = getLayersNoMask(FW2_DATA_DIR + "/Leidos/" + "X_LC_MMAX_ALL_YR", "ews_gen.layer.tpl.map", "EFETAC-NASA_MoMAllYear", ".tif", "no", False)
LAYERS3_NOMASK = LAYERS3_NOMASK + LAYERS3_NOMASK_FW2_LEIDOS
#print "debug: at 13"

LAYERS4 = getLayers(DATA_DIR + "/fsdata/efetac_nasa/"+ "X_LC_ALLYEAR", "ews_gen.layer.tpl.map", "EFETAC-NASA_AllYear", ".tif", "no", True)
LAYERS4_NOMASK = getLayersNoMask(DATA_DIR + "/fsdata/efetac_nasa/"+ "X_LC_ALLYEAR", "ews_gen.layer.tpl.map", "EFETAC-NASA_AllYear", ".tif", "no", False)
LAYERS4_NOMASK_FW2_LEIDOS = getLayersNoMask(FW2_DATA_DIR + "/Leidos/" + "X_LC_ALLYEAR", "ews_gen.layer.tpl.map", "EFETAC-NASA_AllYear", ".tif", "no", False)
LAYERS4_NOMASK = LAYERS4_NOMASK + LAYERS4_NOMASK_FW2_LEIDOS

###
### write out ews.map, using EPSG 3857 (WebMercator),
### and ewswgs84, using EPSG 4326, and ewswcs, for serving WCS (using MapServer 6):
###

#This was used when all layers were combined into the one ews service which was taken down
LAYERSCOMBINED = LAYERS1 + LAYERS2 + LAYERS3

#This service is no longer being written due to getting pegged
# mapTemplate = Template("ews.map.tmpl")
# SERVICE_NAME = "ews"
# f_new = openMapfileForWriting("ews.map")
# f_new.write( mapTemplate.render( {
            # 'DATA_DIR'                : DATA_DIR,
            # 'LAYERS'                  : LAYERSCOMBINED,
            # 'WMS_SRS'                 : "EPSG:3857 EPSG:4326 EPSG:900913",
            # 'MAPFILE_PROJECTION'      : '"init=epsg:3857"',
            # 'SERVICE_NAME'            : SERVICE_NAME,
            # 'TEMP_FILE_PREFIX'        : "ms_%s" % (SERVICE_NAME),
            # 'MAPFILE'                 : "%s/msconfig/%s.map" % (BASE_DIR, SERVICE_NAME),
            # 'OWS_TITLE'               : "NEMAC %s WMS" % (SERVICE_NAME),
            # 'OWS_ABSTRACT'            : "NEMAC %s WMS" % (SERVICE_NAME),
            # 'OWS_KEYWORDLIST'         : "mapserver,ogc,%s" % (SERVICE_NAME),
            # 'SERVICE_URL'             : "%s/%s" % (SERVER_URL, SERVICE_NAME),
            # 'MS_ERRORFILE'            : "../var/log/%s.log" % (SERVICE_NAME),
            # 'WFS_NAMESPACE_PREFIX'    : SERVICE_NAME
            # } ) )
# f_new.close()

mapTemplate = Template("ews.map.tmpl")
SERVICE_NAME = "muc"
f_new = openMapfileForWriting("muc.map")
f_new.write( mapTemplate.render( {
            'DATA_DIR'                : DATA_DIR,
            'LAYERS'                  : LAYERS2_NOMASK,
            'WMS_SRS'                 : "EPSG:3857 EPSG:4326 EPSG:900913",
            'MAPFILE_PROJECTION'      : '"init=epsg:3857"',
            'SERVICE_NAME'            : SERVICE_NAME,
            'TEMP_FILE_PREFIX'        : "ms_%s" % (SERVICE_NAME),
            'MAPFILE'                 : "%s/msconfig/%s.map" % (BASE_DIR, SERVICE_NAME),
            'OWS_TITLE'               : "NEMAC %s WMS" % (SERVICE_NAME),
            'OWS_ABSTRACT'            : "NEMAC %s WMS" % (SERVICE_NAME),
            'OWS_KEYWORDLIST'         : "mapserver,ogc,%s" % (SERVICE_NAME),
            'SERVICE_URL'             : "%s/%s" % (SERVER_URL, SERVICE_NAME),
            'MS_ERRORFILE'            : "../var/log/%s.log" % (SERVICE_NAME),
            'WFS_NAMESPACE_PREFIX'    : SERVICE_NAME
            } ) )
f_new.close()

mapTemplate = Template("ews.map.tmpl")
SERVICE_NAME = "mmax"
f_new = openMapfileForWriting("mmax.map")
f_new.write( mapTemplate.render( {
            'DATA_DIR'                : DATA_DIR,
            'LAYERS'                  : LAYERS3_NOMASK,
            'WMS_SRS'                 : "EPSG:3857 EPSG:4326 EPSG:900913",
            'MAPFILE_PROJECTION'      : '"init=epsg:3857"',
            'SERVICE_NAME'            : SERVICE_NAME,
            'TEMP_FILE_PREFIX'        : "ms_%s" % (SERVICE_NAME),
            'MAPFILE'                 : "%s/msconfig/%s.map" % (BASE_DIR, SERVICE_NAME),
            'OWS_TITLE'               : "NEMAC %s WMS" % (SERVICE_NAME),
            'OWS_ABSTRACT'            : "NEMAC %s WMS" % (SERVICE_NAME),
            'OWS_KEYWORDLIST'         : "mapserver,ogc,%s" % (SERVICE_NAME),
            'SERVICE_URL'             : "%s/%s" % (SERVER_URL, SERVICE_NAME),
            'MS_ERRORFILE'            : "../var/log/%s.log" % (SERVICE_NAME),
            'WFS_NAMESPACE_PREFIX'    : SERVICE_NAME
            } ) )
f_new.close()

mapTemplate = Template("ews.map.tmpl")
SERVICE_NAME = "max"
f_new = openMapfileForWriting("max.map")
f_new.write( mapTemplate.render( {
            'DATA_DIR'                : DATA_DIR,
            'LAYERS'                  : LAYERS4_NOMASK,
            'WMS_SRS'                 : "EPSG:3857 EPSG:4326 EPSG:900913",
            'MAPFILE_PROJECTION'      : '"init=epsg:3857"',
            'SERVICE_NAME'            : SERVICE_NAME,
            'TEMP_FILE_PREFIX'        : "ms_%s" % (SERVICE_NAME),
            'MAPFILE'                 : "%s/msconfig/%s.map" % (BASE_DIR, SERVICE_NAME),
            'OWS_TITLE'               : "NEMAC %s WMS" % (SERVICE_NAME),
            'OWS_ABSTRACT'            : "NEMAC %s WMS" % (SERVICE_NAME),
            'OWS_KEYWORDLIST'         : "mapserver,ogc,%s" % (SERVICE_NAME),
            'SERVICE_URL'             : "%s/%s" % (SERVER_URL, SERVICE_NAME),
            'MS_ERRORFILE'            : "../var/log/%s.log" % (SERVICE_NAME),
            'WFS_NAMESPACE_PREFIX'    : SERVICE_NAME
            } ) )
f_new.close()

# template = Template("ews_gen.tpl.map")
# f_new = openMapfileForAppending("ews.map")
# SERVICE_NAME = "ews"
# WCS_LABEL = ""
# f_new.write( template.render( {
            # 'DATA_DIR'              : DATA_DIR,
            # 'SERVICE_URL'           : "%s/%s" % (SERVER_URL, "ews1year"),
            # 'LAYERS'                : LAYERS,
            # 'WMS_SRS'               : "EPSG:4326 EPSG:2163 EPSG:3857 EPSG:900913",
            # 'MAPFILE_PROJECTION'    : '"init=epsg:3857"',
            # 'SERVICE_NAME'          : SERVICE_NAME,
            # 'TEMP_FILE_PREFIX'      : "ms_%s" % (SERVICE_NAME),
            # 'MAPFILE'               : "%s/msconfig/%s.map" % (BASE_DIR, SERVICE_NAME),
            # 'OWS_TITLE'             : "NEMAC %s WMS" % (SERVICE_NAME),
            # 'OWS_ABSTRACT'          : "NEMAC %s WMS" % (SERVICE_NAME),
            # 'OWS_KEYWORDLIST'       : "mapserver,ogc,%s" % (SERVICE_NAME),
            # 'SERVICE_URL'           : "%s/%s" % (SERVER_URL, SERVICE_NAME),
            # 'MS_ERRORFILE'          : "../var/log/%s.log" % (SERVICE_NAME),
            # 'WFS_NAMESPACE_PREFIX'  : SERVICE_NAME, 
            # 'WCS_LABEL'             : WCS_LABEL
            # } ) )
# f_new.close()

#print "debug: at 15"

#This service is no longer being written due to getting pegged
# f_new = openMapfileForWriting("ewswgs84.map")
# SERVICE_NAME = "ewswgs84"
# f_new.write( mapTemplate.render( {
            # 'DATA_DIR'                : DATA_DIR,
            # 'LAYERS'                  : LAYERS,
            # 'WMS_SRS'                 : "EPSG:4326 EPSG:900913",
            # 'MAPFILE_PROJECTION'      : '"init=epsg:4326"',
            # 'SERVICE_NAME'            : SERVICE_NAME,
            # 'TEMP_FILE_PREFIX'        : "ms_%s" % (SERVICE_NAME),
            # 'MAPFILE'                 : "%s/msconfig/%s.map" % (BASE_DIR, SERVICE_NAME),
            # 'OWS_TITLE'               : "NEMAC %s WMS" % (SERVICE_NAME),
            # 'OWS_ABSTRACT'            : "NEMAC %s WMS" % (SERVICE_NAME),
            # 'OWS_KEYWORDLIST'         : "mapserver,ogc,%s" % (SERVICE_NAME),
            # 'SERVICE_URL'             : "%s/%s" % (SERVER_URL, SERVICE_NAME),
            # 'MS_ERRORFILE'            : "../var/log/%s.log" % (SERVICE_NAME),
            # 'WFS_NAMESPACE_PREFIX'    : SERVICE_NAME
            # } ) )
# f_new.close()

#print "debug: at 16"

wcslayerTemplate = Template("ewswcs.layer.tmpl")
LAYERS = ""
for tifdict in tiflist:
    if tifdict['PROJVALID']:
        LAYERS = LAYERS + wcslayerTemplate.render( tifdict )
        
#print "debug: at 17"

f_new = openMapfileForWriting("ewswcs.map")
SERVICE_NAME = "ewswcs"
f_new.write( mapTemplate.render( {
            'DATA_DIR'                : DATA_DIR,
            'LAYERS'                  : LAYERS,
#           'EPSG'                    : "2163",
            'WMS_SRS'                 : "EPSG:2163",
            'MAPFILE_PROJECTION'      : '"init=epsg:2163"',
            'SERVICE_NAME'            : SERVICE_NAME,
            'TEMP_FILE_PREFIX'        : "ms_%s" % (SERVICE_NAME),
            'MAPFILE'                 : "%s/msconfig/%s.map" % (BASE_DIR, SERVICE_NAME),
            'OWS_TITLE'               : "NEMAC %s WCS" % (SERVICE_NAME),
            'OWS_ABSTRACT'            : "NEMAC %s WCS" % (SERVICE_NAME),
            'OWS_KEYWORDLIST'         : "mapserver,ogc,%s" % (SERVICE_NAME),
            'SERVICE_URL'             : "%s/%s" % (SERVER_URL, SERVICE_NAME),
            'MS_ERRORFILE'            : "../var/log/%s.log" % (SERVICE_NAME),
            'WFS_NAMESPACE_PREFIX'    : SERVICE_NAME
            } ) )
f_new.close()


#print "debug: at 18"

###-------DONE WITH curr, prev1 and prev2 SECTION except that All Year is done above------------------
###-------Now on with the 1, 3 and All year parts-----------------------------------------------------


###
### CREATE ewswcs1year.map FILE:
###
LAYERS = getLayers(DATA_DIR + "/fsdata/efetac_nasa/"+ "X_LC_1YEAR", "ews_gen.layer.tpl.map", "EFETAC-NASA_1Year", ".tif", "yes", False)
# Add new Leidos layers living in /fsdata3
LAYERS_FW2_LEIDOS = getLayers(FW2_DATA_DIR + "/Leidos/" + "X_LC_1YEAR", "ews_gen.layer.tpl.map", "EFETAC-NASA_1Year", ".tif", "yes", False)
LAYERS = LAYERS + LAYERS_FW2_LEIDOS
template = Template("ews_gen.tpl.map")
f_new = openMapfileForWriting("ewswcs1year.map")
SERVICE_NAME = "ewswcs1year"
WCS_LABEL = "EWS 1Year"
f_new.write( template.render( {
            'DATA_DIR'              : DATA_DIR,
            'SERVICE_URL'           : "%s/%s" % (SERVER_URL, "ewswcs1year"),
            'LAYERS'                : LAYERS,
            'WMS_SRS'               : "EPSG:2163",
            'MAPFILE_PROJECTION'    : '"init=epsg:2163"',
            'SERVICE_NAME'          : SERVICE_NAME,
            'TEMP_FILE_PREFIX'      : "ms_%s" % (SERVICE_NAME),
            'MAPFILE'               : "%s/msconfig/%s.map" % (BASE_DIR, SERVICE_NAME),
            'OWS_TITLE'             : "NEMAC %s WMS" % (SERVICE_NAME),
            'OWS_ABSTRACT'          : "NEMAC %s WMS" % (SERVICE_NAME),
            'OWS_KEYWORDLIST'       : "mapserver,ogc,%s" % (SERVICE_NAME),
            'SERVICE_URL'           : "%s/%s" % (SERVER_URL, SERVICE_NAME),
            'MS_ERRORFILE'          : "../var/log/%s.log" % (SERVICE_NAME),
            'WFS_NAMESPACE_PREFIX'  : SERVICE_NAME, 
            'WCS_LABEL'             : WCS_LABEL
            } ) )
f_new.close()


###
### Create the ewswcs3year.map file:
###
LAYERS = getLayers(DATA_DIR + "/fsdata/efetac_nasa/X_LC_3YEAR", "ews_gen.layer.tpl.map", "EFETAC-NASA_3Year", ".tif", "yes", False)
LAYERS_FW2_LEIDOS = getLayers(FW2_DATA_DIR + "/Leidos/" + "X_LC_3YEAR", "ews_gen.layer.tpl.map", "EFETAC-NASA_3Year", ".tif", "yes", False)
LAYERS = LAYERS + LAYERS_FW2_LEIDOS
template = Template("ews_gen.tpl.map")
f_new = openMapfileForWriting("ewswcs3year.map")
SERVICE_NAME = "ewswcs3year"
WCS_LABEL = "EWS 3Year"
f_new.write( template.render( {
            'DATA_DIR'              : DATA_DIR,
            'SERVICE_URL'           : "%s/%s" % (SERVER_URL, "ewswcs3year"),
            'LAYERS'                : LAYERS,
            'WMS_SRS'               : "EPSG:2163",
            'MAPFILE_PROJECTION'    : '"init=epsg:2163"',
            'SERVICE_NAME'          : SERVICE_NAME,
            'TEMP_FILE_PREFIX'      : "ms_%s" % (SERVICE_NAME),
            'MAPFILE'               : "%s/msconfig/%s.map" % (BASE_DIR, SERVICE_NAME),
            'OWS_TITLE'             : "NEMAC %s WMS" % (SERVICE_NAME),
            'OWS_ABSTRACT'          : "NEMAC %s WMS" % (SERVICE_NAME),
            'OWS_KEYWORDLIST'       : "mapserver,ogc,%s" % (SERVICE_NAME),
            'SERVICE_URL'           : "%s/%s" % (SERVER_URL, SERVICE_NAME),
            'MS_ERRORFILE'          : "../var/log/%s.log" % (SERVICE_NAME),
            'WFS_NAMESPACE_PREFIX'  : SERVICE_NAME, 
            'WCS_LABEL'             : WCS_LABEL
            } ) )
f_new.close()


###
### Create the ewswcs5year.map file:
###
LAYERS = getLayers(DATA_DIR + "/fsdata/efetac_nasa/X_LC_5YEAR", "ews_gen.layer.tpl.map", "EFETAC-NASA_5Year", ".tif", "yes", False)
LAYERS_FW2_LEIDOS = getLayers(FW2_DATA_DIR + "/Leidos/" + "X_LC_5YEAR", "ews_gen.layer.tpl.map", "EFETAC-NASA_5Year", ".tif", "yes", False)
LAYERS = LAYERS + LAYERS_FW2_LEIDOS
template = Template("ews_gen.tpl.map")
f_new = openMapfileForWriting("ewswcs5year.map")
SERVICE_NAME = "ewswcs5year"
WCS_LABEL = "EWS 5Year"
f_new.write( template.render( {
            'DATA_DIR'              : DATA_DIR,
            'SERVICE_URL'           : "%s/%s" % (SERVER_URL, "ewswcs5year"),
            'LAYERS'                : LAYERS,
            'WMS_SRS'               : "EPSG:2163",
            'MAPFILE_PROJECTION'    : '"init=epsg:2163"',
            'SERVICE_NAME'          : SERVICE_NAME,
            'TEMP_FILE_PREFIX'      : "ms_%s" % (SERVICE_NAME),
            'MAPFILE'               : "%s/msconfig/%s.map" % (BASE_DIR, SERVICE_NAME),
            'OWS_TITLE'             : "NEMAC %s WMS" % (SERVICE_NAME),
            'OWS_ABSTRACT'          : "NEMAC %s WMS" % (SERVICE_NAME),
            'OWS_KEYWORDLIST'       : "mapserver,ogc,%s" % (SERVICE_NAME),
            'SERVICE_URL'           : "%s/%s" % (SERVER_URL, SERVICE_NAME),
            'MS_ERRORFILE'          : "../var/log/%s.log" % (SERVICE_NAME),
            'WFS_NAMESPACE_PREFIX'  : SERVICE_NAME, 
            'WCS_LABEL'             : WCS_LABEL
            } ) )
f_new.close()

###
### CREATE ews1year.map FILE:
###
LAYERS1 = getLayers(DATA_DIR + "/fsdata/efetac_nasa/"+ "X_LC_1YEAR", "ews_gen.layer.tpl.map", "EFETAC-NASA_1Year", ".tif", "no", True)
LAYERS1_NOMASK = getLayersNoMask(DATA_DIR + "/fsdata/efetac_nasa/"+ "X_LC_1YEAR", "ews_gen.layer.tpl.map", "EFETAC-NASA_1Year", ".tif", "no", False)
LAYERS1_FW2_LEIDOS_NOMASK = getLayersNoMask(FW2_DATA_DIR + "/Leidos/" + "X_LC_1YEAR", "ews_gen.layer.tpl.map", "EFETAC-NASA_1Year", ".tif", "no", False)
LAYERS1_NOMASK = LAYERS1_NOMASK + LAYERS1_FW2_LEIDOS_NOMASK
# template = Template("ews_gen.tpl.map")
# #print LAYERS
# f_new = openMapfileForWriting("ews1year.map")
# SERVICE_NAME = "ews1year"
# WCS_LABEL = "EWS 1Year"
# f_new.write( template.render( {
            # 'DATA_DIR'              : DATA_DIR,
            # 'SERVICE_URL'           : "%s/%s" % (SERVER_URL, "ews1year"),
            # 'LAYERS'                : LAYERS,
            # 'WMS_SRS'               : "EPSG:4326 EPSG:2163 EPSG:3857 EPSG:900913",
            # 'MAPFILE_PROJECTION'    : '"init=epsg:3857"',
            # 'SERVICE_NAME'          : SERVICE_NAME,
            # 'TEMP_FILE_PREFIX'      : "ms_%s" % (SERVICE_NAME),
            # 'MAPFILE'               : "%s/msconfig/%s.map" % (BASE_DIR, SERVICE_NAME),
            # 'OWS_TITLE'             : "NEMAC %s WMS" % (SERVICE_NAME),
            # 'OWS_ABSTRACT'          : "NEMAC %s WMS" % (SERVICE_NAME),
            # 'OWS_KEYWORDLIST'       : "mapserver,ogc,%s" % (SERVICE_NAME),
            # 'SERVICE_URL'           : "%s/%s" % (SERVER_URL, SERVICE_NAME),
            # 'MS_ERRORFILE'          : "../var/log/%s.log" % (SERVICE_NAME),
            # 'WFS_NAMESPACE_PREFIX'  : SERVICE_NAME, 
            # 'WCS_LABEL'             : WCS_LABEL
            # } ) )
# f_new.close()

#print "debug: at 19"

###
### Append to ews1year.map FILE Early Detect (ALC) Change from previous year:
###
LAYERS2 = getLayers(DATA_DIR + "/fsdata/efetac_nasa/"+ "X_LC_ALC_1YR", "ews_gen.layer.tpl.map", "EFETAC-NASA_ALC1YR", ".tif", "no", True)
LAYERS2_NOMASK = getLayersNoMask(DATA_DIR + "/fsdata/efetac_nasa/"+ "X_LC_ALC_1YR", "ews_gen.layer.tpl.map", "EFETAC-NASA_ALC1YR", ".tif", "no", False)
LAYERS2_FW2_LEIDOS_NOMASK = getLayersNoMask(FW2_DATA_DIR + "/Leidos/" + "X_LC_ALC_1YR", "ews_gen.layer.tpl.map", "EFETAC-NASA_ALC1YR", ".tif", "no", False)
LAYERSCOMBINED = LAYERS1 + LAYERS2
LAYERSCOMBINED_NOMASK = LAYERS1_NOMASK + LAYERS2_NOMASK + LAYERS2_FW2_LEIDOS_NOMASK
template = Template("ews_gen.tpl.map")
f_new = openMapfileForWriting("ews1year.map")
SERVICE_NAME = "ews1year"
WCS_LABEL = "EWS 1Year"
f_new.write( template.render( {
            'DATA_DIR'              : DATA_DIR,
            'SERVICE_URL'           : "%s/%s" % (SERVER_URL, "ews1year"),
            'LAYERS'                : LAYERSCOMBINED_NOMASK,
            'WMS_SRS'               : "EPSG:4326 EPSG:2163 EPSG:3857 EPSG:900913",
            'MAPFILE_PROJECTION'    : '"init=epsg:3857"',
            'SERVICE_NAME'          : SERVICE_NAME,
            'TEMP_FILE_PREFIX'      : "ms_%s" % (SERVICE_NAME),
            'MAPFILE'               : "%s/msconfig/%s.map" % (BASE_DIR, SERVICE_NAME),
            'OWS_TITLE'             : "NEMAC %s WMS" % (SERVICE_NAME),
            'OWS_ABSTRACT'          : "NEMAC %s WMS" % (SERVICE_NAME),
            'OWS_KEYWORDLIST'       : "mapserver,ogc,%s" % (SERVICE_NAME),
            'SERVICE_URL'           : "%s/%s" % (SERVER_URL, SERVICE_NAME),
            'MS_ERRORFILE'          : "../var/log/%s.log" % (SERVICE_NAME),
            'WFS_NAMESPACE_PREFIX'  : SERVICE_NAME, 
            'WCS_LABEL'             : WCS_LABEL
            } ) )
f_new.close()

#print "debug: at 20"

#print "debug: at 21"

###
### Create the ews3year.map file:
###
LAYERS = getLayers(DATA_DIR + "/fsdata/efetac_nasa/"+ "X_LC_3YEAR", "ews_gen.layer.tpl.map", "EFETAC-NASA_3Year", ".tif", "no", True)
LAYERS_NOMASK = getLayersNoMask(DATA_DIR + "/fsdata/efetac_nasa/"+ "X_LC_3YEAR", "ews_gen.layer.tpl.map", "EFETAC-NASA_3Year", ".tif", "no", False)
LAYERS_FW2_LEIDOS_NOMASK = getLayersNoMask(FW2_DATA_DIR + "/Leidos/" + "X_LC_3YEAR", "ews_gen.layer.tpl.map", "EFETAC-NASA_3Year", ".tif", "no", False)
LAYERS_NOMASK = LAYERS_NOMASK + LAYERS_FW2_LEIDOS_NOMASK
template = Template("ews_gen.tpl.map")
f_new = openMapfileForWriting("ews3year.map")
SERVICE_NAME = "ews3year"
WCS_LABEL = "EWS 3Year"
f_new.write( template.render( {
            'DATA_DIR'              : DATA_DIR,
            'SERVICE_URL'           : "%s/%s" % (SERVER_URL, "ews3year"),
            'LAYERS'                : LAYERS_NOMASK,
            'WMS_SRS'               : "EPSG:4326 EPSG:2163 EPSG:3857 EPSG:900913",
            'MAPFILE_PROJECTION'    : '"init=epsg:3857"',
            'SERVICE_NAME'          : SERVICE_NAME,
            'TEMP_FILE_PREFIX'      : "ms_%s" % (SERVICE_NAME),
            'MAPFILE'               : "%s/msconfig/%s.map" % (BASE_DIR, SERVICE_NAME),
            'OWS_TITLE'             : "NEMAC %s WMS" % (SERVICE_NAME),
            'OWS_ABSTRACT'          : "NEMAC %s WMS" % (SERVICE_NAME),
            'OWS_KEYWORDLIST'       : "mapserver,ogc,%s" % (SERVICE_NAME),
            'SERVICE_URL'           : "%s/%s" % (SERVER_URL, SERVICE_NAME),
            'MS_ERRORFILE'          : "../var/log/%s.log" % (SERVICE_NAME),
            'WFS_NAMESPACE_PREFIX'  : SERVICE_NAME, 
            'WCS_LABEL'             : WCS_LABEL
            } ) )
f_new.close()

#print "debug: at 22"

###
### Create the ews5year.map file:
###
LAYERS = getLayers(DATA_DIR + "/fsdata/efetac_nasa/"+ "X_LC_5YEAR", "ews_gen.layer.tpl.map", "EFETAC-NASA_5Year", ".tif", "no", True)
LAYERS_NOMASK = getLayersNoMask(DATA_DIR + "/fsdata/efetac_nasa/"+ "X_LC_5YEAR", "ews_gen.layer.tpl.map", "EFETAC-NASA_5Year", ".tif", "no", False)
LAYERS_FW2_LEIDOS_NOMASK = getLayersNoMask(FW2_DATA_DIR + "/Leidos/" + "X_LC_5YEAR", "ews_gen.layer.tpl.map", "EFETAC-NASA_5Year", ".tif", "no", False)
LAYERS_NOMASK = LAYERS_NOMASK + LAYERS_FW2_LEIDOS_NOMASK
template = Template("ews_gen.tpl.map")
f_new = openMapfileForWriting("ews5year.map")
SERVICE_NAME = "ews5year"
WCS_LABEL = "EWS 5Year"
f_new.write( template.render( {
            'DATA_DIR'              : DATA_DIR,
            'SERVICE_URL'           : "%s/%s" % (SERVER_URL, "ews5year"),
            'LAYERS'                : LAYERS_NOMASK,
            'WMS_SRS'               : "EPSG:4326 EPSG:2163 EPSG:3857 EPSG:900913",
            'MAPFILE_PROJECTION'    : '"init=epsg:3857"',
            'SERVICE_NAME'          : SERVICE_NAME,
            'TEMP_FILE_PREFIX'      : "ms_%s" % (SERVICE_NAME),
            'MAPFILE'               : "%s/msconfig/%s.map" % (BASE_DIR, SERVICE_NAME),
            'OWS_TITLE'             : "NEMAC %s WMS" % (SERVICE_NAME),
            'OWS_ABSTRACT'          : "NEMAC %s WMS" % (SERVICE_NAME),
            'OWS_KEYWORDLIST'       : "mapserver,ogc,%s" % (SERVICE_NAME),
            'SERVICE_URL'           : "%s/%s" % (SERVER_URL, SERVICE_NAME),
            'MS_ERRORFILE'          : "../var/log/%s.log" % (SERVICE_NAME),
            'WFS_NAMESPACE_PREFIX'  : SERVICE_NAME, 
            'WCS_LABEL'             : WCS_LABEL
            } ) )
f_new.close()

#print "debug: at 22"
#create the all year dyna_ews map files
LAYERS = getLayers(DATA_DIR + "/fsdata/efetac_nasa/"+ "X_LC_ALLYEAR", "ews_gen.layer.tpl.map", "EFETAC-NASA", ".tif", "no", True)
#print "debug: at 23"


#print "debug: at 24"

###
### Create the vlayers.map file:
###
template = Template("vlayers.tpl.map")
f_new = openMapfileForWriting("vlayers.map")
f_new.write( template.render( {
            'DATA_DIR'     : DATA_DIR,
            'POSTGIS_CONNECTION_STRING' : POSTGIS_CONNECTION_STRING,
            'SERVICE_URL'  : "%s/%s" % (SERVER_URL, "vlayers")
            } ) )
f_new.close()

#print "debug: at 25"

###
### Create the derivatives.map file:
###
template = Template("derivatives.tpl.map")
f_new = openMapfileForWriting("derivatives.map")
f_new.write( template.render( {
            'DATA_DIR'     : DATA_DIR,
            'SERVICE_URL'  : "%s/%s" % (SERVER_URL, "derivatives")
            } ) )
f_new.close()

#print "debug: at 26"

###
### Create the modisndvi.map file:
###
template = Template("modisndvi.tpl.map")
f_new = openMapfileForWriting("modisndvi.map")
f_new.write( template.render( {
            'DATA_DIR'     : DATA_DIR,
            'SERVICE_URL'  : "%s/%s" % (SERVER_URL, "modisndvi")
            } ) )
f_new.close()

#print "debug: at 27"

###
### Create the parameters.map file:
###
template = Template("parameters.tpl.map")
f_new = openMapfileForWriting("parameters.map")
f_new.write( template.render( {
            'DATA_DIR'     : DATA_DIR,
            'SERVICE_URL'  : "%s/%s" % (SERVER_URL, "parameters")
            } ) )
f_new.close()

#print "debug: at 28"

###
### Create the integrals.map file:
###
template = Template("integrals.tpl.map")
f_new = openMapfileForWriting("integrals.map")
f_new.write( template.render( {
            'DATA_DIR'     : DATA_DIR,
            'SERVICE_URL'  : "%s/%s" % (SERVER_URL, "integrals")
            } ) )
f_new.close()

#print "debug: at 29"

###
### Create the rlayers.map file:
###
template = Template("rlayers.tpl.map")
f_new = openMapfileForWriting("rlayers.map")
f_new.write( template.render( {
            'DATA_DIR'     : DATA_DIR,
            'SERVICE_URL'  : "%s/%s" % (SERVER_URL, "rlayers")
            } ) )
f_new.close()

###
### Create the landcover-mask.map file:
###
template = Template("landcover-mask.tpl.map")
f_new = openMapfileForWriting("landcover-mask.map")
f_new.write( template.render( {
            'DATA_DIR'     : DATA_DIR,
            'SERVICE_URL'  : "%s/%s" % (SERVER_URL, "landcover-mask")
            } ) )
f_new.close()

#print "debug: at 30"

###
### Create the wlayers.map file:
###
template = Template("wlayers.tpl.map")
f_new = openMapfileForWriting("wlayers.map")
f_new.write( template.render( {
            'DATA_DIR'     : DATA_DIR,
            'SERVICE_URL'  : "%s/%s" % (SERVER_URL, "wlayers")
            } ) )
f_new.close()

###
### Create the aklayers.map file:
###
template = Template("aklayers.tpl.map")
f_new = openMapfileForWriting("aklayers.map")
f_new.write( template.render( {
            'DATA_DIR'     : DATA_DIR,
            'SERVICE_URL'  : "%s/%s" % (SERVER_URL, "aklayers")
            } ) )
f_new.close()

###
### Create the duration.map file:
###
template = Template("duration.tpl.map")
f_new = openMapfileForWriting("duration.map")
f_new.write( template.render( {
            'DATA_DIR'     : DATA_DIR,
            'SERVICE_URL'  : "%s/%s" % (SERVER_URL, "duration")
            } ) )
f_new.close()

###
### Create the treatments.map file:
###
template = Template("treatments.tpl.map")
f_new = openMapfileForWriting("treatments.map")
f_new.write( template.render( {
            'DATA_DIR'     : DATA_DIR,
            'POSTGIS_CONNECTION_STRING' : POSTGIS_CONNECTION_STRING,
            'SERVICE_URL'  : "%s/%s" % (SERVER_URL, "treatments")
            } ) )
f_new.close()

###
### Create the phenoregions.map file:
###
template = Template("phenoregions.tpl.map")
f_new = openMapfileForWriting("phenoregions.map")
f_new.write( template.render( {
            'DATA_DIR'     : DATA_DIR,
            'SERVICE_URL'  : "%s/%s" % (SERVER_URL, "phenoregions")
            } ) )
f_new.close()

###
### Create the boundaries.map file:
###
template = Template("boundaries.tpl.map")
f_new = openMapfileForWriting("boundaries.map")
f_new.write( template.render( {
            'DATA_DIR'     : DATA_DIR,
            'POSTGIS_CONNECTION_STRING' : POSTGIS_CONNECTION_STRING,
            'SERVICE_URL'  : "%s/%s" % (SERVER_URL, "boundaries")
            } ) )
f_new.close()

###
### Create the fire.map file:
###
template = Template("fire.tpl.map")
f_new = openMapfileForWriting("fire.map")
f_new.write( template.render( {
            'DATA_DIR'     : DATA_DIR,
            'POSTGIS_CONNECTION_STRING' : POSTGIS_CONNECTION_STRING,
            'SERVICE_URL'  : "%s/%s" % (SERVER_URL, "fire")
            } ) )
f_new.close()

###
### Create the ads.map file:
###
template = Template("ads.tpl.map")
f_new = openMapfileForWriting("ads.map")
f_new.write( template.render( {
            'DATA_DIR'     : DATA_DIR,
            'POSTGIS_CONNECTION_STRING' : POSTGIS_CONNECTION_STRING,
            'SERVICE_URL'  : "%s/%s" % (SERVER_URL, "ads")
            } ) )
f_new.close()

###
### Create the forwarn-ndvi-change.map file:
###
template = Template("forwarn-ndvi-change.tpl.map")
f_new = openMapfileForWriting("forwarn-ndvi-change.map")
f_new.write( template.render( {
            'DATA_DIR'     : DATA_DIR,
            'POSTGIS_CONNECTION_STRING' : POSTGIS_CONNECTION_STRING,
            'SERVICE_URL'  : "%s/%s" % (SERVER_URL, "forwarn-ndvi-change")
            } ) )
f_new.close()

#################################################################################################

#print "debug: at 31"

###
### Create symlinks for the map files, and change a few permission settings
###
os.system("(cd ../html ; ln -f -s ../msconfig/ews.map . ; ln -f -s ../msconfig/ewswgs84.map . ; ln -f -s ../msconfig/ewswcs.map .)")
os.system("chmod a+w ../var/log");
os.system("chmod a+w ../var/log/*.log > /dev/null 2>&1");
os.system("chmod g-w ../html/*");

#print "debug: at 32"

###
### write out the layer titles file:
###
f_out = open("layerTitles.txt", "w");
for layerName in layerTitles:
    f_out.write("%s:%s\n" % (layerName, layerTitles[layerName]))
f_out.close()

#print "debug: at 33"

###
### write out the html/index.html file:
###
FSWMS_VERSION = subprocess.Popen(['../version'], stdout=subprocess.PIPE).communicate()[0].strip()
f_out = open("../html/index.html", "w");
f_out.write(interp("""
<table width="100%"><tr>
<td align="left">This is ForWarn version #{FSWMS_VERSION}.</td>
<td align="right">Viewer: <a href="view/index.html">view/index.html</a>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Config file: <a href="view/config/ews_config.xml">view/config/ews_config.xml</a></td>
</tr></table>
<p>
ForWarn WMS addresses are:
<ul>
"""))

#print "debug: at 34"

for mapfile in mapfilesWritten:
    service = re.sub(r'\.map$', '', mapfile)
    f_out.write(interp("""<li><a href="#{SERVER_URL}/%(SERVICE)s">#{SERVER_URL}/%(SERVICE)s</a> [ <a href="#{SERVER_URL}/%(SERVICE)s?SERVICE=WMS&REQUEST=GetCapabilities">GetCapabilities</a> ]\n""" %
                       { "SERVICE" : service }))

f_out.write(interp("""</ul>\n"""))

f_out.close()



#### FORWARN II #####

ALL_PRODUCT_TYPES = PRODUCT_TYPES.copy()
ALL_PRODUCT_TYPES.update(LEGACY_PRODUCT_TYPES)


def getFW2Layers(dataDir, product_type, layerTemplateName, fileExt, wcs, maskBool, source='', period=''):
    tifList  = []
    files = sorted([file for file in os.listdir(dataDir) if file.endswith(fileExt)], reverse=False)

    if period:
        files = list(filter(lambda x: period in x, files))

    for tif in files:
        dynaList  = []
        try:
            tif = re.sub('^' + dataDir + '/', '', tif)
            tif_fullpath = dataDir + '/' + tif;
            proj = getproj(tif_fullpath)

            if period:
                layerName = '{0}_{1}_{2}'.format(SOURCES[source], PRODUCT_TYPES[product_type], period)
            else:
                layerName = re.sub(r'^.*/', '', tif)

            if product_type == 'X_LC_PCTPROGRESS':
              colormapline = 'INCLUDE "percent_progress_color_table.cmap"'
            else:
              colormapline = 'INCLUDE "new-forwarn2-standard-2.cmap"'

            tifList.append({ 'TIF'             : tif,
                             'PROJVALID'       : len(proj) > 0,
                             'PROJ'            : formatproj(proj,10),
                             'WKT'             : getwkt(tif_fullpath),
                             'NAME'            : layerName,
                             'DATA'            : dataDir + '/' + tif,
                             'TITLE'           : layerName,
                             'ABSTRACT'        : layerName,
                             'COLORMAPLINE'    : colormapline,
                             'MASK'            : '',
                             })

            layerTitles[layerName] = layerName

            if maskBool:
                for mask in ewsMask:
                    tifList.append({ 'TIF'             : tif,
                                     'PROJVALID'       : len(proj) > 0,
                                     'PROJ'            : formatproj(proj,10),
                                     'WKT'             : getwkt(tif_fullpath),
                                     'NAME'            : layerName + mask['name'],
                                     'DATA'            : dataDir + '/' + tif,
                                     'TITLE'           : layerName + mask['name'],
                                     'ABSTRACT'        : layerName + mask['name'],
                                     'COLORMAPLINE'    : colormapline,
                                     'MASK'            : 'MASK ' + mask['name'],
                                     })
            layerTemplate = Template(layerTemplateName)
            layers = ""

        except Exception as e:
            print e
            continue

    layerTemplate = Template(layerTemplateName)
    layers = ""

    for tifdict in tifList:
        if tifdict['PROJVALID']:
            layers = layers + layerTemplate.render(tifdict)    

    return layers


def makeCurrentMapfilesFor(source, product_type):
    path = os.path.join(VIEWER_LINK_TARGET_DIR, source, product_type)
    periods = [ 'current', 'previous1', 'previous2' ]
    for period in periods:
        LAYERS = getFW2Layers(path, product_type, "ews_gen.layer.tpl.map", ".img", "no", True, source, period)
        template = Template("ews_gen.tpl.map")
        layerName = '{0}_{1}_{2}'.format(SOURCES[source], ALL_PRODUCT_TYPES[product_type], period)
        mapfile_path = "forwarn2_maps/"+layerName+".map"
        try:
            os.remove(mapfile_path)
        except:
            pass
        f_new = open(mapfile_path, "w")
        f_new.write( template.render( {
                    'DATA_DIR'              : DATA_DIR,
                    'SERVICE_URL'           : "%s/%s" % (SERVER_URL, 'forwarn_compare'),
                    'LAYERS'                : LAYERS,
                    'WMS_SRS'               : "EPSG:4326 EPSG:2163 EPSG:3857 EPSG:900913",
                    'MAPFILE_PROJECTION'    : '"init=epsg:3857"',
                    'SERVICE_NAME'          : 'forwarn_compare',
                    'TEMP_FILE_PREFIX'      : "ms_%s" % (layerName),
                    'MAPFILE'               : "%s/msconfig/%s.map" % (BASE_DIR, layerName),
                    'OWS_TITLE'             : "NEMAC %s WMS" % (layerName),
                    'OWS_ABSTRACT'          : "NEMAC %s WMS" % (layerName),
                    'OWS_KEYWORDLIST'       : "mapserver,ogc,%s" % (layerName),
                    'SERVICE_URL'           : "%s/%s" % (SERVER_URL, 'forwarn_compare'),
                    'MS_ERRORFILE'          : "../var/log/%s.log" % (layerName),
                    'WFS_NAMESPACE_PREFIX'  : layerName, 
                    'WCS_LABEL'             : layerName
                    } ) )
        f_new.close()


def makeBundledMapfileFor(source, product_type, cgi_endpoint):
    print cgi_endpoint + '.map'
    groupName = SOURCES[source]+ALL_PRODUCT_TYPES[product_type]
    LAYERS = getFW2Layers(os.path.join(FW2_DATA_DIR, source, product_type), product_type, "ews_gen.layer.tpl.map", ".img", "no", True)
    template = Template("ews_gen.tpl.map")
    f_new = openMapfileForWriting('{0}.map'.format(cgi_endpoint))
    SERVICE_NAME = cgi_endpoint
    WCS_LABEL = groupName
    f_new.write( template.render( {
                'DATA_DIR'              : DATA_DIR,
                'SERVICE_URL'           : "%s/%s" % (SERVER_URL, SERVICE_NAME),
                'LAYERS'                : LAYERS,
                'WMS_SRS'               : "EPSG:4326 EPSG:2163 EPSG:3857 EPSG:900913",
                'MAPFILE_PROJECTION'    : '"init=epsg:3857"',
                'SERVICE_NAME'          : SERVICE_NAME,
                'TEMP_FILE_PREFIX'      : "ms_%s" % (SERVICE_NAME),
                'MAPFILE'               : "%s/msconfig/%s.map" % (BASE_DIR, SERVICE_NAME),
                'OWS_TITLE'             : "NEMAC %s WMS" % (SERVICE_NAME),
                'OWS_ABSTRACT'          : "NEMAC %s WMS" % (SERVICE_NAME),
                'OWS_KEYWORDLIST'       : "mapserver,ogc,%s" % (SERVICE_NAME),
                'SERVICE_URL'           : "%s/%s" % (SERVER_URL, SERVICE_NAME),
                'MS_ERRORFILE'          : "../var/log/%s.log" % (SERVICE_NAME),
                'WFS_NAMESPACE_PREFIX'  : SERVICE_NAME, 
                'WCS_LABEL'             : WCS_LABEL
                } ) )
    f_new.close()



def makeLID(source, product_type, date_string, sources=SOURCES, product_types=ALL_PRODUCT_TYPES):
  return '_'.join([
    'FW',
    date_string,
    product_types[product_type],
    sources[source]
  ])

def makeFW2MapfilesFor(source, p_type):
  pwd = os.path.join(FW2_DATA_DIR, source, p_type)
  if not os.path.exists(pwd):
    return

  for f in os.listdir(pwd):
    products = []

    if not f.endswith(('tif', 'img')):
        continue

    print f

    f_path = os.path.join(pwd, f)
    
    # Assume a string of 8 digits in the filename is the date formatted as %Y%m%d
    match = re.search(r"(\d{8})", f)
    if not match:
      continue

    date_string = str(match.groups(1)[0])

    lid = makeLID(source, p_type, date_string)
    proj = getproj(f_path)
    if p_type == 'X_LC_PCTPROGRESS':
      colormapline = 'INCLUDE "percent_progress_color_table.cmap"'
    else:
      colormapline = 'INCLUDE "new-forwarn2-standard-2.cmap"'
    products.append({
             'NAME'            : lid,
             'PROJ'            : formatproj(proj,10),
             'DATA'            : f_path,
             'COLORMAPLINE'    : colormapline,
             'TITLE'           : lid,
             'ABSTRACT'        : lid,
             'MASK'            : '',
    })
    for mask in ewsMask:
      products.append({
               'NAME'            : lid + mask['name'],
               'PROJ'            : formatproj(proj,10),
               'DATA'            : f_path,
               'COLORMAPLINE'    : colormapline,
               'TITLE'           : lid + mask['name'],
               'ABSTRACT'        : lid + mask['name'],
               'MASK'            : 'MASK ' + mask['name'],
      })

    layerTemplate = Template('ews_gen.layer.tpl.map')
    layers = ""

    for props in products:
        layers = layers + layerTemplate.render(props)    
        mapTemplate = Template("ews.map.tmpl")
        SERVICE_NAME = "forwarn_compare"
        f_new = open("forwarn2_maps/"+lid+".map", "w")
        f_new.write(mapTemplate.render({
              'DATA_DIR'                : DATA_DIR,
              'LAYERS'                  : layers,
              'MS_ERRORFILE'            : "../var/log/%s.log" % (SERVICE_NAME),
              'WMS_SRS'                 : "EPSG:3857 EPSG:4326",
              'MAPFILE_PROJECTION'      : '"init=epsg:3857"',
              'TEMP_FILE_PREFIX'        : "ms_%s" % (SERVICE_NAME),
              'OWS_TITLE'               : "NEMAC %s WMS" % (SERVICE_NAME),
              'OWS_ABSTRACT'            : "NEMAC %s WMS" % (SERVICE_NAME),
              'SERVICE_URL'             : "%s/%s" % (SERVER_URL, SERVICE_NAME),
          })
        )
        f_new.close()                    


for s in SOURCES:
    for p in ALL_PRODUCT_TYPES:
        makeFW2MapfilesFor(s, p)

for s in FW2_SOURCES:
    for p in PRODUCT_TYPES:
        if s == 'ForWarn2_Sqrt' and p == 'X_LC_PCTPROGRESS':
            continue
        cgi_endpoint = '{0}_{1}'.format(FW2_SOURCES[s], PRODUCT_TYPES[p])
        makeBundledMapfileFor(s, p, cgi_endpoint)
        makeCurrentMapfilesFor(s, p)
